variables:
    GIT_DEPTH: "1"

stages:
    - mil-internal-release_build
    - prepare_mil-internal-release_debs

mil-internal-release_build:
    tags:
        - Runner-Buster
    stage: mil-internal-release_build
    script:
        - dpkg --add-architecture armhf
        - dpkg --add-architecture arm64
        - dpkg --add-architecture amd64
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20201211/debian/ buster main" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install --allow-unauthenticated -y
          crossbuild-essential-armhf libc6-dev:armhf
          crossbuild-essential-arm64 libc6-dev:arm64
          build-essential:amd64 libc6-dev:amd64
        - dpkg-buildpackage -us -uc -b -aarmhf
        - dpkg-buildpackage -us -uc -b -aarm64
        - dpkg-buildpackage -us -uc -b -aamd64
        - mv ../*.buildinfo .
        - mv ../*.changes .
        - mv ../*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.buildinfo
        - ./*.changes
        - ./*.deb

prepare_mil-internal-release_debs:
    tags:
        - Runner-Buster
    stage: prepare_mil-internal-release_debs
    only:
      refs:
        - buster/master
    dependencies:
        - mil-internal-release_build
    when: manual
    script:
        - mkdir -p /cache/buster/mil-internal-release/
        - cp *.deb /cache/buster/mil-internal-release/
        - ls /cache/buster/mil-internal-release/
